catalogs:
  build:
    publint: 0.3.24
    typescript: 7.0.2
    unplugin-unused: 0.6.0
  types:
    "@types/node": 24.13.3
  vite:
    vite: npm:@voidzero-dev/vite-plus-core@0.2.8
    vite-plus: 0.2.8
overrides:
  vite: "catalog:vite"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
